# Linear Regression – Normal Equation

## Module 1 – Import Libraries

In [1]:
import numpy as np

## Module 2 – Create Dataset

In [2]:
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

y = np.array([
    25000, 30000, 35000, 40000, 45000,
    50000, 55000, 60000, 65000, 70000
])

print("Experience (X):")
print(X)

print("\nSalary (y):")
print(y)

Experience (X):
[ 1  2  3  4  5  6  7  8  9 10]

Salary (y):
[25000 30000 35000 40000 45000 50000 55000 60000 65000 70000]


## Module 3 – Add Bias / Intercept

In [3]:
X_b = np.c_[np.ones(len(X)), X]

print("X with Bias / Intercept:")
print(X_b)

X with Bias / Intercept:
[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]]


## Module 4 – Calculate Normal Equation

In [4]:
theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

print("Theta:")
print(theta)

Theta:
[20000.  5000.]


## Module 5 – Get Intercept and Slope

In [5]:
b0 = theta[0]
b1 = theta[1]

print("Intercept:", b0)
print("Slope:", b1)

Intercept: 20000.000000000007
Slope: 5000.000000000001


## Module 6 – Prediction for All Training Data

In [6]:
y_pred = X_b @ theta

print("Predicted Salaries:")
print(y_pred)

Predicted Salaries:
[25000. 30000. 35000. 40000. 45000. 50000. 55000. 60000. 65000. 70000.]


## Module 7 – Compare Actual and Predicted Salaries

In [7]:
print("Actual Salaries:")
print(y)

print("\nPredicted Salaries:")
print(y_pred)

Actual Salaries:
[25000 30000 35000 40000 45000 50000 55000 60000 65000 70000]

Predicted Salaries:
[25000. 30000. 35000. 40000. 45000. 50000. 55000. 60000. 65000. 70000.]


## Module 8 – Predict Salary for 7.5 Years Experience

In [8]:
experience = 7.5

prediction = b0 + b1 * experience

print("Experience:", experience)
print("Predicted salary for 7.5 years:", prediction)

Experience: 7.5
Predicted salary for 7.5 years: 57500.000000000015


## Module 9 – Complete

In [9]:
print("Linear Regression using Normal Equation completed successfully.")

Linear Regression using Normal Equation completed successfully.
